package udv.compi;

import java_cup.runtime.*;

class Parser;

terminal LLA, LLC, CA, CC, DP, COMMA, COMILLA;
terminal String VAL, ID;
terminal String NUM;

non terminal S, L, LP, V;

start with L;

L ::= L COMMA NUM:n{:if(Integer.parseInt(n)%2 == 0){
					System.out.print("par ");
				}else{
					System.out.print("impar ");
				}
		:}
	|NUM:n {: if(Integer.parseInt(n)%2 == 0){
					System.out.print("par ");
				}else{
					System.out.print("impar ");
				}
		:};
			
	